services:

  db:
    image: postgres:14
    container_name: db_students
    environment:
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db_students
    volumes:
      - ./db/dump:/var/lib/postgresql/data

  api:
    build: api
    container_name: api
    ports:
      - "3000:8000"
    environment:
      DATABASE_URL: "postgresql://my_user:pass@db/db_students"
    depends_on:
      - db

  fronted:
    build:
      context: ./fronted
      dockerfile: Dockerfile
    container_name: fronted
    ports:
      - "80:80"
    depends_on:
      - api

volumes:
  dump:
    external: false