services:
#  nginx:
#    build: fronted/nginx
#    container_name: nginx
#    ports:
#      - "80:80"
#    networks:
#      - app-network
#    depends_on:
#      - website
#      - chat
#    volumes:
#      - ./nginx/logs:/var/log/nginx

  db:
    image: postgres:14
    container_name: db_students
    environment:
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db_students
    volumes:
      - ./db/dump:/var/lib/postgresql/data
#    networks:
#      - app-network

  api:
    build: api
    container_name: api
#    networks:
#      - app-network
    ports:
      - "3000:8000"
    environment:
      DATABASE_URL: "postgresql://my_user:pass@db/db_students"
    depends_on:
      - db

  fronted:
    build:
      context: ./fronted
      dockerfile: Dockerfile
    container_name: fronted
    ports:
      - "80:80"
    depends_on:
      - api

#
#networks:
#  app-network:
#    driver: bridge

volumes:
  dump:
    external: false